Repository DongneHankki/DongneHankki-BE, pull requests merged in 2025-07, with the labels that each got.

#14 [FEATURE] #12 Global Setting
  build.gradle
  src/main/java/org/netway/dongnehankki/DongneHankkiBeApplication.java
  src/main/java/org/netway/dongnehankki/global/common/ApiResponse.java
  src/main/java/org/netway/dongnehankki/global/common/BaseEntity.java
  src/main/java/org/netway/dongnehankki/global/config/JpaConfig.java
  src/main/java/org/netway/dongnehankki/global/config/SwaggerConfig.java
  src/main/java/org/netway/dongnehankki/global/exception/CustomException.java
  src/main/java/org/netway/dongnehankki/global/exception/ErrorCode.java
  src/main/java/org/netway/dongnehankki/global/exception/GlobalExceptionHandler.java
  src/main/java/org/netway/dongnehankki/post/domain/Comment.java
  src/main/java/org/netway/dongnehankki/post/domain/Post.java
  src/main/java/org/netway/dongnehankki/store/domain/Menu.java
  src/main/java/org/netway/dongnehankki/store/domain/Review.java
  src/main/java/org/netway/dongnehankki/store/domain/Store.java
  src/main/java/org/netway/dongnehankki/user/domain/User.java
  src/main/resources/application.yml
Labels: setting, feature

#18 [FEATURE] #6 User 회원 가입 및 JWT 로그인 적용
  .gitignore
  build.gradle
  src/main/java/org/netway/dongnehankki/global/auth/CustomUserDetails.java
  src/main/java/org/netway/dongnehankki/global/auth/CustomUserDetailsService.java
  src/main/java/org/netway/dongnehankki/global/auth/SecurityConfig.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/JwtAuthenticationHandler.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/JwtAuthorizationHandler.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/RefreshToken.java
  src/main/java/org/netway/dongnehankki/global/auth/jwt/RefreshTokenRepository.java
  src/main/java/org/netway/dongnehankki/global/exception/CustomException.java
  src/main/java/org/netway/dongnehankki/global/exception/GlobalExceptionHandler.java
  src/main/java/org/netway/dongnehankki/global/exception/store/UnregisteredStoreException.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/StoreRepository.java
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/java/org/netway/dongnehankki/user/domain/User.java
  src/main/java/org/netway/dongnehankki/user/dto/login/LoginRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/login/LoginResponse.java
  src/main/java/org/netway/dongnehankki/user/dto/login/RefreshTokenRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/response/UserResponse.java
  src/main/java/org/netway/dongnehankki/user/dto/signUp/CustomerSignUpRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/signUp/OwnerSignUpRequest.java
  src/main/java/org/netway/dongnehankki/user/exception/DuplicateUserNameException.java
  src/main/java/org/netway/dongnehankki/user/exception/InvalidPasswordException.java
  src/main/java/org/netway/dongnehankki/user/exception/InvalidRefreshTokenException.java
  src/main/java/org/netway/dongnehankki/user/exception/UnregisteredUserException.java
  src/main/java/org/netway/dongnehankki/user/infrastructure/UserRepository.java
  src/main/java/org/netway/dongnehankki/user/presentation/UserController.java
  src/main/resources/application.yml
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/fixture/CustomerUserFixture.java
  src/test/java/org/netway/dongnehankki/user/fixture/OwnerUserFixture.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
Labels: feature

#19 [FEATURE] #13 - 지도 기반 상점 조회 기능 추가
  build.gradle
  src/main/java/org/netway/dongnehankki/map/application/MapBoundaryCalculator.java
  src/main/java/org/netway/dongnehankki/map/application/MapBoundingBox.java
  src/main/java/org/netway/dongnehankki/map/application/MapService.java
  src/main/java/org/netway/dongnehankki/map/dto/request/MapRequest.java
  src/main/java/org/netway/dongnehankki/map/dto/response/MapResponse.java
  src/main/java/org/netway/dongnehankki/map/presentation/MapController.java
  src/main/java/org/netway/dongnehankki/store/application/.gitkeep
  src/main/java/org/netway/dongnehankki/store/domain/Store.java
  src/main/java/org/netway/dongnehankki/store/dto/request/.gitkeep
  src/main/java/org/netway/dongnehankki/store/dto/response/.gitkeep
  src/main/java/org/netway/dongnehankki/store/exception/UnregisteredStoreException.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/StoreRepository.java
  src/main/java/org/netway/dongnehankki/store/presentation/.gitkeep
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/test/java/org/netway/dongnehankki/map/application/MapBoundaryCalculatorTest.java
  src/test/java/org/netway/dongnehankki/map/application/MapServiceTest.java
  src/test/java/org/netway/dongnehankki/map/presentation/MapControllerTest.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/StoreRepository.java
Labels: feature

#20 [FEATURE] #6 User 조회 API 기능 추가
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/java/org/netway/dongnehankki/user/dto/response/UserResponse.java
  src/main/java/org/netway/dongnehankki/user/presentation/UserController.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
Labels: feature

#22 [FEATURE] #6 User 수정 API 구현
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/java/org/netway/dongnehankki/user/domain/User.java
  src/main/java/org/netway/dongnehankki/user/dto/request/CustomerSignUpRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/request/LoginRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/request/LoginResponse.java
  src/main/java/org/netway/dongnehankki/user/dto/request/OwnerSignUpRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/request/RefreshTokenRequest.java
  src/main/java/org/netway/dongnehankki/user/dto/request/UpdateUserRequest.java
  src/main/java/org/netway/dongnehankki/user/exception/DuplicateNickNameException.java
  src/main/java/org/netway/dongnehankki/user/exception/DuplicateUserIdException.java
  src/main/java/org/netway/dongnehankki/user/exception/EmptyNickNameException.java
  src/main/java/org/netway/dongnehankki/user/infrastructure/UserRepository.java
  src/main/java/org/netway/dongnehankki/user/presentation/UserController.java
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
Labels: feature

#24 [refactor]#15 PR시에는 CI만 동작하도록 설정
  .github/workflows/deploy-to-server.yml
  src/main/java/org/netway/dongnehankki/global/config/SwaggerConfig.java
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/resources/application.yml
  src/test/java/org/netway/dongnehankki/DongneHankkiBeApplicationTests.java
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
  src/test/resources/application-test.yml
Labels: deploy

#26 [FEATURE]#6 User Soft Delete 기능 구현
  build.gradle
  gradlew
  src/main/java/org/netway/dongnehankki/global/common/BaseEntity.java
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/java/org/netway/dongnehankki/user/domain/User.java
  src/main/java/org/netway/dongnehankki/user/presentation/UserController.java
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
Labels: feature

#27 [TEST]#6 User API TEST 커버리지 100% 달성
  src/main/java/org/netway/dongnehankki/user/dto/request/RefreshTokenRequest.java
  src/test/java/org/netway/dongnehankki/global/auth/CustomUserDetailsServiceTest.java
  src/test/java/org/netway/dongnehankki/global/auth/CustomUserDetailsTest.java
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
Labels: refactor

#28 [Feature] #9 공공데이터포털에서 가맹점 데이터 받아오는 scheduler 추가
  src/main/java/org/netway/dongnehankki/global/config/RestClientConfig.java
  src/main/java/org/netway/dongnehankki/global/config/ScheduleConfig.java
  src/main/java/org/netway/dongnehankki/map/application/MapService.java
  src/main/java/org/netway/dongnehankki/map/dto/response/MapResponse.java
  src/main/java/org/netway/dongnehankki/store/application/.gitkeep
  src/main/java/org/netway/dongnehankki/store/application/StoreDataService.java
  src/main/java/org/netway/dongnehankki/store/application/StoreSyncService.java
  src/main/java/org/netway/dongnehankki/store/domain/Store.java
  src/main/java/org/netway/dongnehankki/store/dto/response/.gitkeep
  src/main/java/org/netway/dongnehankki/store/dto/response/StoreOpenApiResponse.java
  src/main/java/org/netway/dongnehankki/store/exception/OpenApiException.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/external/StoreOpenApiClient.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/external/StoreOpenApiParser.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/repository/StoreRepository.java
  src/main/java/org/netway/dongnehankki/user/application/UserService.java
  src/main/resources/application.yml
  src/test/java/org/netway/dongnehankki/DongneHankkiBeApplicationTests.java
  src/test/java/org/netway/dongnehankki/global/config/ScheduleConfigTest.java
  src/test/java/org/netway/dongnehankki/map/application/MapServiceTest.java
  src/test/java/org/netway/dongnehankki/store/application/StoreDataServiceTest.java
  src/test/java/org/netway/dongnehankki/store/application/StoreSyncServiceTest.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/StoreRepository.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/external/StoreOpenApiClientTest.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/external/StoreOpenApiParserTest.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/repository/StoreRepository.java
  src/test/java/org/netway/dongnehankki/user/application/UserServiceTest.java
  src/test/java/org/netway/dongnehankki/user/presentation/UserControllerTest.java
  src/test/resources/application-test.yml
Labels: feature

#29 [REFACTOR]#9 store test 커버리지 리팩토링
  src/main/java/org/netway/dongnehankki/store/application/StoreDataService.java
  src/test/java/org/netway/dongnehankki/store/application/StoreDataServiceTest.java
Labels: refactor

#30 [REFACTOR] #13 store entity industyCode, businessNumber type 각각 Integer, Long으로 변경
  src/main/java/org/netway/dongnehankki/map/dto/response/MapResponse.java
  src/main/java/org/netway/dongnehankki/store/application/StoreDataService.java
  src/main/java/org/netway/dongnehankki/store/domain/Store.java
  src/main/java/org/netway/dongnehankki/store/infrastructure/repository/StoreRepository.java
  src/test/java/org/netway/dongnehankki/map/application/MapServiceTest.java
  src/test/java/org/netway/dongnehankki/store/application/StoreDataServiceTest.java
  src/test/java/org/netway/dongnehankki/store/infrastructure/repository/StoreRepository.java
Labels: refactor
